name: GitHub Actions Demo
on:
  push:
    branches:
      - main  

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python job.py  
        
      - name: Print workflow status
        run: echo "🍏 This job's status is ${{ job.status }}."
